# Generated by Django 6.0.6 on 2026-06-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('Guide', 'Guide'), ('News', 'News'), ('Tips', 'Tips'), ('Review', 'Review')], max_length=50)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('views', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('internship', 'Internship Paper'), ('thesis', 'Thesis Paper'), ('term', 'Term Paper'), ('project', 'Project Paper')], max_length=50)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('views', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('region', models.CharField(choices=[('asia', 'Asia'), ('north-america', 'North America'), ('south-america', 'South America'), ('europe', 'Europe')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
