# Generated by Django 6.0.6 on 2026-06-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_blogpost_views_alter_paper_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='views',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='views',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='views',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
