# Generated by Django 6.0.6 on 2026-06-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_blogpost_views_alter_paper_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='views',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='views',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='views',
        ),
    ]
