# Generated by Django 6.0.6 on 2026-06-18 15:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_blogpost_content_alter_paper_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
