# Generated by Django 6.0.6 on 2026-06-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_blogpost_excerpt_alter_paper_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='description',
            field=models.TextField(),
        ),
    ]
