from django.core.management.base import BaseCommand
from myapp.models import Paper, BlogPost, Scholarship
from datetime import date


class Command(BaseCommand):
    help = 'Seed database with sample scholarships, blog posts and papers'

    def handle(self, *args, **options):
        self._seed_scholarships()
        self._seed_blog_posts()
        self._seed_papers()
        self.stdout.write(self.style.SUCCESS('All data seeded successfully!'))

    def _seed_scholarships(self):
        Scholarship.objects.all().delete()
        scholarships = [
            Scholarship(title='MEXT Scholarship 2026 — Fully Funded to Japan', slug='mext-scholarship-2026-japan', region='asia', country='Japan', description='The Japanese Government MEXT Scholarship offers full tuition, monthly allowance, and airfare for international students to study at Japanese universities.', content='<h3>Eligibility</h3><p>Applicants must hold a bachelor\'s degree and be under 35 years of age. Strong academic record required.</p><h3>Benefits</h3><ul><li>Full tuition coverage</li><li>Monthly stipend of ¥145,000</li><li>Round-trip airfare</li><li>Free accommodation</li></ul>', deadline=date(2026, 10, 31)),
            Scholarship(title='Chinese Government Scholarship — Study in China', slug='chinese-government-scholarship-2026', region='asia', country='China', description='Full scholarship by the Chinese Ministry of Education covering tuition, accommodation, health insurance and monthly stipend.', content='<h3>Eligibility</h3><p>Open to all international students. Must have high school diploma or bachelor\'s degree depending on program.</p>', deadline=date(2026, 5, 30)),
            Scholarship(title='DAAD Scholarship — Study in South Korea', slug='daad-scholarship-south-korea', region='asia', country='South Korea', description='DAAD Korea offers scholarships for graduate studies at Korean universities with full funding.', content='', deadline=date(2026, 8, 15)),
            Scholarship(title='Singapore International Graduate Award (SINGA)', slug='singa-scholarship-singapore', region='asia', country='Singapore', description='SINGA offers fully funded PhD positions in science and engineering at top Singapore universities.', content='<h3>Benefits</h3><p>Full tuition, monthly stipend of SGD 2,000, settling-in allowance, airfare.</p>', deadline=date(2026, 6, 1)),
            Scholarship(title='Erasmus Mundus Joint Masters Scholarship', slug='erasmus-mundus-scholarship-2026', region='europe', country='Multiple Countries', description='Full scholarship for joint master programmes across multiple European universities with travel and living costs covered.', content='<h3>What is Covered</h3><p>Full tuition, monthly allowance of 1000 EUR, travel costs, installation costs.</p>', deadline=date(2026, 2, 15)),
            Scholarship(title='Chevening Scholarship — Study in the UK', slug='chevening-scholarship-uk-2026', region='europe', country='United Kingdom', description='Fully funded UK government scholarship for one-year master\'s degrees, covering tuition, living expenses, and airfare.', content='<h3>Eligibility</h3><p>Applicants must have a strong academic background, leadership potential, and at least two years of work experience.</p>', deadline=date(2026, 11, 5)),
            Scholarship(title='DAAD Scholarship — Study in Germany 2026', slug='daad-scholarship-germany-2026', region='europe', country='Germany', description='Fully funded DAAD scholarships for international students to pursue master\'s or PhD in Germany.', content='', deadline=date(2026, 9, 30)),
            Scholarship(title='Swiss Government Excellence Scholarship', slug='swiss-excellence-scholarship-2026', region='europe', country='Switzerland', description='Full scholarship for PhD and postdoctoral researchers at Swiss universities.', content='<h3>Benefits</h3><p>Monthly stipend, tuition exemption, health insurance, airfare.</p>', deadline=date(2026, 12, 15)),
            Scholarship(title='Fulbright Program — Study in the USA', slug='fulbright-scholarship-usa-2026', region='north-america', country='United States', description='Prestigious US government scholarship for graduate study, research, and teaching assistantships.', content='<h3>Coverage</h3><p>Full tuition, living stipend, health insurance, airfare, visa support.</p>', deadline=date(2026, 10, 10)),
            Scholarship(title='Vanier Canada Graduate Scholarship', slug='vanier-scholarship-canada-2026', region='north-america', country='Canada', description='$50,000 per year for three years for PhD students at Canadian universities.', content='', deadline=date(2026, 11, 1)),
            Scholarship(title='Trudeau Foundation Scholarship — Canada', slug='trudeau-scholarship-canada', region='north-america', country='Canada', description='Full scholarship for PhD students in social sciences and humanities at Canadian universities.', content='<h3>Benefits</h3><p>$60,000 annual stipend, travel and networking funds.</p>', deadline=date(2026, 2, 28)),
            Scholarship(title='AAUW International Fellowship — USA', slug='aauw-fellowship-usa', region='north-america', country='United States', description='Fellowships for women to pursue graduate or postgraduate study in the United States.', content='', deadline=date(2026, 11, 15)),
            Scholarship(title='OAS Academic Scholarship — Study in Brazil', slug='oas-scholarship-brazil', region='south-america', country='Brazil', description='Full scholarship for graduate studies in Brazil offered by the Organization of American States.', content='<h3>Eligibility</h3><p>Open to OAS member countries. Covers tuition, living expenses and health insurance.</p>', deadline=date(2026, 7, 31)),
            Scholarship(title='CONICYT Scholarship — Chile', slug='conicyt-scholarship-chile', region='south-america', country='Chile', description='Chilean government scholarship for international students at accredited Chilean universities.', content='', deadline=date(2026, 8, 30)),
            Scholarship(title='AlBan Scholarship — Study in Argentina', slug='alban-scholarship-argentina', region='south-america', country='Argentina', description='Full scholarship for Latin American students to pursue postgraduate studies in Argentina.', content='<h3>Coverage</h3><p>Full tuition, monthly stipend, health insurance, airfare.</p>', deadline=date(2026, 9, 15)),
            Scholarship(title='Colombia Government Scholarship — Study in Colombia', slug='colombia-gov-scholarship', region='south-america', country='Colombia', description='ICETEX scholarship for international students to pursue master\'s and PhD programs in Colombia.', content='', deadline=date(2026, 6, 20)),
        ]
        Scholarship.objects.bulk_create(scholarships)
        self.stdout.write(f'Created {len(scholarships)} scholarships')

    def _seed_blog_posts(self):
        BlogPost.objects.all().delete()
        posts = [
            BlogPost(title='How to Write a Winning Scholarship Essay', slug='winning-scholarship-essay-guide', category='Guide', excerpt='Learn the key strategies to craft a compelling scholarship application essay that stands out.', content='<p>Writing a scholarship essay is your chance to tell your story. Start with a strong opening, highlight your achievements, and explain why you deserve the scholarship. Be authentic and proofread multiple times.</p><p>Most importantly, tailor each essay to the specific scholarship you are applying for.</p>'),
            BlogPost(title='Top 10 Fully Funded Scholarships for 2026', slug='top-10-fully-funded-scholarships-2026', category='News', excerpt='A curated list of the best fully funded scholarships available for international students in 2026.', content='<p>We\'ve compiled the top 10 fully funded scholarships including MEXT, Chevening, Erasmus Mundus, DAAD, and Fulbright. Each offers full tuition and living expenses.</p><p>Apply early and prepare your documents in advance.</p>'),
            BlogPost(title='5 Tips for Acing Your Scholarship Interview', slug='scholarship-interview-tips', category='Tips', excerpt='Prepare with confidence using these expert tips for scholarship interviews.', content='<p>1. Research the scholarship thoroughly. 2. Practice common questions. 3. Dress professionally. 4. Show enthusiasm. 5. Ask thoughtful questions at the end.</p>'),
            BlogPost(title='Study in Germany: A Complete Guide for 2026', slug='study-in-germany-guide-2026', category='Guide', excerpt='Everything you need to know about applying to German universities as an international student.', content='<p>Germany offers world-class education with low or no tuition fees. This guide covers the application process, visa requirements, student visa, blocked account, and health insurance.</p>'),
            BlogPost(title='Difference Between Undergraduate and Graduate Scholarships', slug='undergraduate-vs-graduate-scholarships', category='Guide', excerpt='Understand the key differences in eligibility, benefits, and application process.', content='<p>Undergraduate scholarships focus on high school achievements and extracurriculars. Graduate scholarships emphasize research potential and academic publications.</p>'),
            BlogPost(title='New UK Scholarship Program Announced for Developing Countries', slug='uk-new-scholarship-program-2026', category='News', excerpt='The UK government announces a new £100 million scholarship program for students from developing countries.', content='<p>The new program will fund 5,000 students over five years, covering full tuition, living expenses, and leadership training.</p>'),
            BlogPost(title='How to Get Strong Recommendation Letters', slug='strong-recommendation-letters-guide', category='Tips', excerpt='Tips on choosing the right referees and helping them write impactful recommendation letters.', content='<p>Choose referees who know you well. Provide them with your CV, achievements, and a summary of your goals. Give them at least 4 weeks of notice.</p>'),
            BlogPost(title='Chevening Scholarship Application: Step by Step', slug='chevening-application-step-by-step', category='Guide', excerpt='A detailed walkthrough of the Chevening Scholarship application process.', content='<p>Step 1: Check eligibility. Step 2: Choose courses. Step 3: Prepare documents. Step 4: Write essays. Step 5: Submit before deadline.</p>'),
            BlogPost(title='MEXT Scholarship: What You Need to Know', slug='mext-scholarship-everything', category='Guide', excerpt='Comprehensive guide to the Japanese Government MEXT Scholarship for 2026.', content='<p>The MEXT Scholarship covers full tuition, monthly allowance of ¥145,000, and round-trip airfare. Research and university recommendation pathways available.</p>'),
            BlogPost(title='Balancing Work and Study as a Scholarship Student', slug='work-study-balance-scholarship', category='Tips', excerpt='Practical advice on managing your time effectively while on a scholarship.', content='<p>Create a schedule, set priorities, use campus resources, and don\'t forget self-care. Many scholarships have work-hour limits — know yours.</p>'),
            BlogPost(title='Review: 2026 Erasmus Mundus Programs', slug='erasmus-mundus-2026-review', category='Review', excerpt='An in-depth review of the Erasmus Mundus Joint Master programs available in 2026.', content='<p>Erasmus Mundus offers over 150 joint master programs across Europe. Students study in at least two countries. The scholarship is highly competitive but fully funded.</p>'),
            BlogPost(title='Scholarship Scams: How to Spot and Avoid Them', slug='avoid-scholarship-scams', category='Tips', excerpt='Learn the red flags of scholarship scams to protect yourself during your search.', content='<p>Never pay to apply, avoid guaranteed scholarships, check official websites, and verify program legitimacy before sharing personal information.</p>'),
            BlogPost(title='Fulbright vs Chevening: Which is Right for You?', slug='fulbright-vs-chevening-comparison', category='Review', excerpt='A side-by-side comparison of the two most prestigious government scholarships.', content='<p>Fulbright is for study in the USA; Chevening is for the UK. Both are fully funded but differ in eligibility, application process, and post-scholarship requirements.</p>'),
            BlogPost(title='How to Write a Research Proposal for PhD Scholarships', slug='research-proposal-phd-scholarship', category='Guide', excerpt='Step-by-step guide to crafting a research proposal that wins PhD scholarships.', content='<p>Your research proposal should have a clear title, background, research question, methodology, timeline, and bibliography. Align it with the professor\'s expertise.</p>'),
        ]
        BlogPost.objects.bulk_create(posts)
        self.stdout.write(f'Created {len(posts)} blog posts')

    def _seed_papers(self):
        Paper.objects.all().delete()
        papers = [
            Paper(title='Machine Learning Internship Report at Google', slug='ml-internship-google', category='internship', description='A comprehensive internship report on machine learning projects completed at Google headquarters.', content='<p>During my internship at Google, I worked on natural language processing models for search optimization. I developed a BERT-based classifier that improved query understanding by 12%.</p>'),
            Paper(title='Software Engineering Internship at Microsoft', slug='se-internship-microsoft', category='internship', description='Detailed report of software engineering internship experience at Microsoft Redmond campus.', content='<p>I contributed to the Azure DevOps team, implementing CI/CD pipeline improvements and developing automated testing frameworks used by 500+ engineers.</p>'),
            Paper(title='Data Science Internship at Amazon — Seattle', slug='ds-internship-amazon', category='internship', description='Analysis and outcomes of a data science internship focusing on recommendation systems.', content='<p>Developed a collaborative filtering model for Amazon\'s product recommendation engine, achieving a 15% improvement in click-through rate.</p>'),
            Paper(title='Research Internship at MIT Media Lab', slug='research-internship-mit', category='internship', description='A research-oriented internship report on human-computer interaction projects.', content='<p>Designed and tested wearable haptic feedback devices for navigation assistance for visually impaired users.</p>'),
            Paper(title='Deep Learning for Medical Image Diagnosis', slug='deep-learning-medical-image-thesis', category='thesis', description='Master thesis on using convolutional neural networks for early detection of diseases from medical images.', content='<p>This thesis proposes a novel CNN architecture achieving 97.3% accuracy in detecting lung cancer from CT scans, outperforming existing benchmarks.</p>'),
            Paper(title='Climate Change Impact on Coastal Ecosystems', slug='climate-change-coastal-ecosystems', category='thesis', description='PhD dissertation examining the effects of rising sea temperatures on coastal biodiversity.', content='<p>Over three years of field research across 12 coastal sites in Southeast Asia, this study quantifies ecosystem degradation rates and proposes conservation strategies.</p>'),
            Paper(title='Blockchain for Supply Chain Transparency', slug='blockchain-supply-chain-thesis', category='thesis', description='A thesis exploring how blockchain technology can improve supply chain transparency and traceability.', content='<p>A practical framework for implementing blockchain-based supply chain tracking, tested with a pilot program across three manufacturing partners.</p>'),
            Paper(title='Quantum Computing Algorithms for Optimization', slug='quantum-optimization-algorithms-thesis', category='thesis', description='Theoretical and experimental analysis of quantum algorithms for combinatorial optimization.', content='<p>This thesis demonstrates quantum speedup for specific NP-hard problems using IBM Quantum systems.</p>'),
            Paper(title='Renewable Energy Policies in Europe', slug='renewable-energy-europe-term', category='term', description='A term paper analyzing EU renewable energy policies and their effectiveness.', content='<p>The EU\'s Green Deal and Fit for 55 package have accelerated renewable adoption. This paper evaluates policy outcomes across member states.</p>'),
            Paper(title='Social Media Impact on Adolescent Mental Health', slug='social-media-mental-health-term', category='term', description='Research term paper examining correlation between social media use and mental health in teenagers.', content='<p>Survey of 500 adolescents shows strong correlation between daily social media use exceeding 3 hours and increased anxiety and depression scores.</p>'),
            Paper(title='Economic Analysis of Remote Work Trends', slug='remote-work-economics-term', category='term', description='An economic term paper on the long-term impacts of remote work on productivity and urban development.', content='<p>Analyzing post-pandemic data, the paper finds a 23% increase in productivity for remote workers but widening inequality in career advancement.</p>'),
            Paper(title='Artificial Intelligence in Education', slug='ai-education-term-paper', category='term', description='Exploring the role of AI tools in transforming modern education systems.', content='<p>AI-powered personalized learning platforms show 30% improvement in student outcomes. This paper discusses implementation challenges and ethical considerations.</p>'),
            Paper(title='Smart Waste Management System Using IoT', slug='smart-waste-management-iot-project', category='project', description='A capstone project on IoT-based smart bins for efficient municipal waste collection.', content='<p>Designed and deployed a network of smart bins with ultrasonic sensors and GPS tracking, reducing collection costs by 35% in a pilot city.</p>'),
            Paper(title='E-Commerce Mobile App Development', slug='ecommerce-mobile-app-project', category='project', description='Full-stack development of a cross-platform e-commerce mobile application.', content='<p>Built with Flutter and Firebase, the app supports real-time inventory, secure payments via Stripe, and AI-powered product recommendations.</p>'),
            Paper(title='Autonomous Drone for Agricultural Monitoring', slug='autonomous-drone-agriculture-project', category='project', description='Senior design project building a drone system for crop health monitoring using multispectral imaging.', content='<p>The drone uses NDVI imaging and machine learning to detect crop diseases early, with 88% accuracy across five crop types.</p>'),
        ]
        Paper.objects.bulk_create(papers)
        self.stdout.write(f'Created {len(papers)} papers')
